### ISSUE TITLE
gateway: add missing metrics and traces

### ISSUE THREAD

**Issue by lidel** [ipfs/go-libipfs#154]
Ref. https://github.com/protocol/bifrost-gateway/issues/8

```[tasklist]
### Tasks

- [ ] CAR and Block have histograms: https://github.com/ipfs/go-libipfs/blob/main/gateway/handler.go#L245-L254 
  We should add the same for TAR, DAG-JSON/CBOR and IPNS Record. There should  also be a generic global one, that covers all response types. Right now the only global we have is `gw_first_content_block_get_latency_seconds`, and that ignores the rest of bigger file + processing. 
- [ ] we have spans for most response types ([example for ServeCAR](https://github.com/ipfs/go-libipfs/blob/302b2799386dea7afb72ba0b4c32a5c427215d06/gateway/handler_car.go#L20))
  We should have the same everywhere else (ex: a span seems to be missing in [ipns record](https://github.com/ipfs/go-libipfs/blob/main/gateway/handler_ipns_record.go))
- [ ] Update `/example/gateway/*`   to expose histograms under same path as Kubo (`/debug/metrics/prometheus`)
```
