### ISSUE TITLE
[Milestone] Getting boxo "over the hump"

### ISSUE THREAD

**Issue by BigLep** [ipfs/go-libipfs#196]
## Background
boxo has been in limbo state for a couple of months which doesn't maximize its utility for maintainers and potential consumers and it doesn't instill confidence in existing consumers who are impacted.

This is a tracking issue for the work for getting boxo to a place of providing value for its intended audience and being clear for those involved and affected on what they can expect going forward.

## Done Criteria
The `Tasks` below are completed.  This includes both the various communication pieces and the resulting release in https://github.com/ipfs/boxo/issues/202. 

## Phases
- [x] ⬇️⬇️⬇️ Planning phase ⬇️⬇️⬇️
   - [x] https://github.com/ipfs/boxo/issues/191
   - [x] https://github.com/ipfs/boxo/issues/174
- [x] ⬇️⬇️⬇️ Staging/validation/RC phase ⬇️⬇️⬇️
   - [x] https://github.com/ipfs/boxo/issues/218
   - [x] https://github.com/ipfs/boxo/issues/215
   - [x] Copy in repos listed in https://github.com/ipfs/boxo/issues/202
   - [x] Cut an RC: https://github.com/ipfs/boxo/releases/tag/v0.8.0-rc1
   - [x] Validate consolidation RC with Kubo: https://github.com/ipfs/kubo/pull/9746
   - [x] Validate consolidation RC with Lotus: https://github.com/filecoin-project/lotus/pull/10562
   - [x] https://github.com/ipfs/boxo/issues/291
   - [x] Lotus cleanup: https://github.com/filecoin-project/lotus/pull/10921
   - [x] Validate consolidation RC with ipfs-cluster
- [ ] ⬇️⬇️⬇️ Documentation/community-focus phase ⬇️⬇️⬇️
   - [x] https://github.com/ipfs/boxo/issues/189
   - [x] https://github.com/ipfs/boxo/issues/181
   - [x] Populate the FAQs in https://github.com/ipfs/boxo/issues/190
   - [x] Close out https://github.com/ipfs/kubo/issues/8543 by pointing to this issue
   - [x] https://github.com/ipfs/boxo/issues/170
   - [ ] https://github.com/ipfs/boxo/issues/203
- [x] ⬇️⬇️⬇️ Disruption phase ⬇️⬇️⬇️
   - [x] Make the boxo release with the copy consolidated repos: https://github.com/ipfs/boxo/pull/257
   - [x] for repos in https://github.com/ipfs/boxo/issues/202
      - [x] add "not maintained" README notices
      - [x] deprecated types
      - [x] copy issues

🪧 The "Staging/validation phase" and "Documentation/community-focus phase" can happen in parallel.  They must complete before the "Disruption phase".  

## How can I follow along progress?
Major updates will be posted here.  The tracking of copying in specific repos will occur in https://github.com/ipfs/boxo/issues/202 . 

## Related Items
There are other [topic/project-management](https://github.com/ipfs/boxo/issues?q=label%3Atopic%2Fproject-management) that are being created as part of this endeavor but aren't blockers for meeting the done criteria.

**Comment by BigLep** [comment]
2023-03-09 update:
1. Plans to copy repos into go-libipfs with deprecated types rather than fully migrate them over is being planned per https://github.com/ipfs/go-libipfs/issues/191#issuecomment-1463020752
2. This issue's description has been more fully flushed out with the specific tasks.
3. There will be a lot more activity on this endeavor the week of 2023-03-13 given @ipfs/kubo-maintainers are close to completing https://github.com/ipfs/kubo/issues/9502

**Comment by BigLep** [comment]
I pointed at this from https://github.com/ipfs/kubo/issues/8543#issuecomment-1463070876 

I'm not planning to do any additional communication on this.  Additional comms will happen in the parent tracking issue (https://github.com/ipfs/go-libipfs/issues/196 ) and the other issues therein.

**Comment by BigLep** [comment]
2023-03-10 update: further broke out the tasks in the issue description.  A key tenant is that we don't start adding "not maintained" README notices and deprecated types in repos until all the documentation items in go-libipfs are handled.  When we start signposting more people to go-libipfs, they should get a strong sense that go-libipfs is thought-through and well-maintained (i.e., treated like someone's baby).

**Comment by BigLep** [comment]
2023-03-29 high level update: 
- go-libipfs has been renamed to boxo: see https://github.com/ipfs/boxo/issues/215
- go-car and go-merkledag have been decoupled from boxo: https://github.com/ipfs/boxo/issues/218
- the list of repos that are being copied into boxo has been reviewed and fine tuned.  There is also "not maintained" messaging that will be pasted in each of these repos.  The set of repos and their current status of being copied in is all tracked at https://github.com/ipfs/boxo/issues/202.  That is a key issue to subscribe to if you want more granular updates.

**Comment by BigLep** [comment]
2023-04-06 update: Boxo 0.8.0 was released which has the copied repos included (https://github.com/ipfs/boxo/pull/264 ).  We're continuing to update the tracker above as progress is made.

**Comment by BigLep** [comment]
2023-04-12 update:
Deprecated types and "not maintained" statuses will not be added until the week of 2023-04-24 (after IPFS Thing).

Various docs about this effort have been created or updated:
1. https://github.com/ipfs/boxo/blob/main/README.md
2. https://github.com/ipfs/boxo/blob/main/RELEASE.md
3. https://github.com/ipfs/boxo/wiki/Rationale-of-2023Q1-Repo-Consolidation-Effort
4. https://github.com/ipfs/boxo/wiki/Copied-or-Migrated-Repos-FAQ

**Comment by BigLep** [comment]
Update on where we're at based on 2023-05-25 maintainer conversation:

First off, fully finishing this off isn't done yet.  [The progress this week was to get the readme notices of "not maintained" added to the various repos](https://github.com/ipfs/boxo/issues/202#issuecomment-1563021449).  

To finish this we need to [handle go-car](https://github.com/ipfs/boxo/issues/218) and [get Lotus fully migrated to Boxo](https://github.com/filecoin-project/lotus/pull/10921).

Unfortunately that work is blocked by universes colliding due to global variables.  This will get addressed in https://github.com/ipfs/boxo/issues/291

That is the top next priority as soon as @aschmahmann or @Jorropo finish their other [inflight work on the board](https://github.com/orgs/ipfs/projects/16/views/6).

**Comment by BigLep** [comment]
Everything is done here except for https://github.com/ipfs/boxo/issues/203 .  That still needs to be done, but will get picked up in Q3.  From end user regard, the goals of this issue have been addressed and as a result, I'm going to close it. 
 Thanks to all involved in making this happen.  (Easter egg that PR with readme logo was pushed today: https://github.com/ipfs/boxo/pull/405)
